# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficdata',
            old_name='data',
            new_name='dataString',
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='carCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trafficdata',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
