# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_api', '0002_auto_20170211_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntersectionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('street_name', models.CharField(max_length=1024, null=True)),
            ],
        ),
    ]
