# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_api', '0003_intersectiondata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intersectiondata',
            old_name='street_name',
            new_name='street_a',
        ),
        migrations.AddField(
            model_name='intersectiondata',
            name='street_b',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
