# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_api', '0007_historicaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='timestamp',
            field=models.FloatField(),
        ),
    ]
