# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_api', '0008_auto_20170330_0116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalData',
        ),
    ]
