# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_api', '0009_delete_historicaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.FloatField()),
                ('hour', models.IntegerField()),
                ('cars', models.IntegerField()),
            ],
        ),
    ]
